version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout

      - restore_cache:
          key: v1-dependency-cache-{{ checksum "setup.py" }}-{{ checksum "Makefile" }}

      - run:
          name: install python dependencies
          command: |
            make dependencies

      - save_cache:
          key: v1-dependency-cache-{{ checksum "setup.py" }}-{{ checksum "Makefile" }}
          paths:
            - "venv"

      - run:
          name: run tests
          command: |
            make test
            codecov

      - store_artifacts:
          path: htmlcov/
      
      - store_artifacts:
          path: coverage
          prefix: coverage

workflows:
  version: 2
  build:
    jobs:
      - build

